const FETCH_BASELINE_LIST = 'FETCH_BASELINE_LIST';
const SELECT_BASELINE = 'SELECT_BASELINE';
const SELECT_ONE_BASELINE = 'SELECT_ONE_BASELINE';
const SET_SELECTED_BASELINES = 'SET_SELECTED_BASELINES';
const CLEAR_SELECTED_BASELINES = 'CLEAR_SELECTED_BASELINES';
const DELETE_SELECTED_BASELINES = 'DELETE_SELECTED_BASELINES';
const EXPAND_PARENT_FACT = 'EXPAND_PARENT_FACT';

export default {
    FETCH_BASELINE_LIST,
    SELECT_BASELINE,
    SELECT_ONE_BASELINE,
    SET_SELECTED_BASELINES,
    CLEAR_SELECTED_BASELINES,
    DELETE_SELECTED_BASELINES,
    EXPAND_PARENT_FACT
};
