const FETCH_BASELINE_LIST = 'FETCH_BASELINE_LIST';
const SELECT_BASELINE = 'SELECT_BASELINE';
const SELECT_ONE_BASELINE = 'SELECT_ONE_BASELINE';
const SET_SELECTED_BASELINES = 'SET_SELECTED_BASELINES';
const CLEAR_SELECTED_BASELINES = 'CLEAR_SELECTED_BASELINES';
const FETCH_BASELINE_DATA = 'FETCH_BASELINE_DATA';
const CLEAR_BASELINE_DATA = 'CLEAR_BASELINE_DATA';
const CREATE_BASELINE = 'CREATE_BASELINE';
const PATCH_BASELINE = 'PATCH_BASELINE';
const SET_ID_DELETE = 'SET_ID_DELETE';
const DELETE_BASELINE = 'DELETE_BASELINE';
const EXPAND_PARENT_FACT = 'EXPAND_PARENT_FACT';

export default {
    FETCH_BASELINE_LIST,
    SELECT_BASELINE,
    SELECT_ONE_BASELINE,
    SET_SELECTED_BASELINES,
    CLEAR_SELECTED_BASELINES,
    FETCH_BASELINE_DATA,
    CLEAR_BASELINE_DATA,
    CREATE_BASELINE,
    PATCH_BASELINE,
    SET_ID_DELETE,
    DELETE_BASELINE,
    EXPAND_PARENT_FACT
};
