const OPEN_ADD_SYSTEM_MODAL = 'OPEN_ADD_SYSTEM_MODAL';
const SELECT_ACTIVE_TAB = 'SELECT_ACTIVE_TAB';
const SET_SELECTED_SYSTEMS_COMPARISON = 'SET_SELECTED_SYSTEMS_COMPARISON';
const HANDLE_SYSTEM_SELECTION = 'HANDLE_SYSTEM_SELECTION';
const HANDLE_BASELINE_SELECTION = 'HANDLE_BASELINE_SELECTION';
const HANDLE_HSP_SELECTION = 'HANDLE_HSP_SELECTION';
const CLEAR_ALL_SELECTIONS = 'CLEAR_ALL_SELECTIONS';

export default {
    OPEN_ADD_SYSTEM_MODAL,
    SELECT_ACTIVE_TAB,
    SET_SELECTED_SYSTEMS_COMPARISON,
    HANDLE_SYSTEM_SELECTION,
    HANDLE_BASELINE_SELECTION,
    HANDLE_HSP_SELECTION,
    CLEAR_ALL_SELECTIONS
};
