const OPEN_ADD_SYSTEM_MODAL = 'OPEN_ADD_SYSTEM_MODAL';
const SELECT_ACTIVE_TAB = 'SELECT_ACTIVE_TAB';
const SET_SELECTED_SYSTEMS_COMPARISON = 'SET_SELECTED_SYSTEMS_COMPARISON';

export default {
    OPEN_ADD_SYSTEM_MODAL,
    SELECT_ACTIVE_TAB,
    SET_SELECTED_SYSTEMS_COMPARISON
};
