const TOGGLE_DELETE_NOTIFICATION_MODAL = 'TOGGLE_DELETE_NOTIFICATION_MODAL';
const SET_SYSTEMS_TO_DELETE = 'SET_SYSTEMS_TO_DELETE';
const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';
const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS';

export default {
    TOGGLE_DELETE_NOTIFICATION_MODAL,
    SET_SYSTEMS_TO_DELETE,
    DELETE_NOTIFICATIONS,
    GET_NOTIFICATIONS,
    ADD_NOTIFICATIONS
};
