const SELECT_ENTITY = 'SELECT_ENTITY';
const FETCH_COMPARE = 'FETCH_COMPARE';
const OPEN_ADD_SYSTEM_MODAL = 'OPEN_ADD_SYSTEM_MODAL';
const RESET_SELECTED_SYSTEM_IDS = 'RESET_SELECTED_SYSTEM_IDS';
const OPEN_FILTER_DROPDOWN = 'OPEN_FILTER_DROPDOWN';
const TOGGLE_FACT_SORT = 'TOGGLE_FACT_SORT';
const FILTER_BY_STATE = 'FILTER_BY_STATE';
const FILTER_BY_FACT = 'FILTER_BY_FACT';
const UPDATE_PAGINATION = 'UPDATE_PAGINATION';
const CLEAR_STATE = 'CLEAR_STATE';
const EXPORT_TO_CSV = 'EXPORT_TO_CSV';
const EXPAND_ROW = 'EXPAND_ROW';

export default {
    CLEAR_STATE,
    SELECT_ENTITY,
    FETCH_COMPARE,
    OPEN_ADD_SYSTEM_MODAL,
    RESET_SELECTED_SYSTEM_IDS,
    OPEN_FILTER_DROPDOWN,
    TOGGLE_FACT_SORT,
    FILTER_BY_STATE,
    FILTER_BY_FACT,
    UPDATE_PAGINATION,
    EXPORT_TO_CSV,
    EXPAND_ROW
};
