const FETCH_STATUS = 'FETCH_STATUS';
const FETCH_COMPARE = 'FETCH_COMPARE';
const OPEN_ADD_SYSTEM_MODAL = 'OPEN_ADD_SYSTEM_MODAL';

export default {
    FETCH_STATUS,
    FETCH_COMPARE,
    OPEN_ADD_SYSTEM_MODAL
};
