const SELECT_ENTITY = 'SELECT_ENTITY';
const FETCH_COMPARE = 'FETCH_COMPARE';
const SET_SELECTED_SYSTEM_IDS = 'SET_SELECTED_SYSTEM_IDS';
const TOGGLE_FACT_SORT = 'TOGGLE_FACT_SORT';
const ADD_STATE_FILTER = 'ADD_STATE_FILTER';
const TOGGLE_STATE_SORT = 'TOGGLE_STATE_SORT';
const FILTER_BY_FACT = 'FILTER_BY_FACT';
const HANDLE_FACT_FILTER = 'HANDLE_FACT_FILTER';
const CLEAR_ALL_FACT_FILTERS = 'CLEAR_ALL_FACT_FILTERS';
const UPDATE_DRIFT_PAGINATION = 'UPDATE_DRIFT_PAGINATION';
const CLEAR_COMPARISON = 'CLEAR_COMPARISON';
const CLEAR_COMPARISON_FILTERS = 'CLEAR_COMPARISON_FILTERS';
const EXPORT_TO_CSV = 'EXPORT_TO_CSV';
const EXPAND_ROW = 'EXPAND_ROW';
const REVERT_COMPARE_DATA = 'REVERT_COMPARE_DATA';
const TOGGLE_ACTIVE_SORT = 'TOGGLE_ACTIVE_SORT';
const UPDATE_REFERENCE_ID = 'UPDATE_REFERENCE_ID';
const SELECT_SINGLE_HSP = 'SELECT_SINGLE_HSP';
const UPDATE_COLUMNS = 'UPDATE_COLUMNS';
const SET_GLOBAL_FILTER_TAGS = 'SET_GLOBAL_FILTER_TAGS';
const SET_GLOBAL_FILTER_WORKLOADS = 'SET_GLOBAL_FILTER_WORKLOADS';
const SET_GLOBAL_FILTER_SIDS = 'SET_GLOBAL_FILTER_SIDS';
const DRIFT_CLEAR_ALL_FILTERS = 'DRIFT_CLEAR_ALL_FILTERS';

export default {
    SELECT_ENTITY,
    FETCH_COMPARE,
    SET_SELECTED_SYSTEM_IDS,
    TOGGLE_FACT_SORT,
    ADD_STATE_FILTER,
    TOGGLE_STATE_SORT,
    FILTER_BY_FACT,
    HANDLE_FACT_FILTER,
    CLEAR_ALL_FACT_FILTERS,
    UPDATE_DRIFT_PAGINATION,
    CLEAR_COMPARISON,
    CLEAR_COMPARISON_FILTERS,
    EXPORT_TO_CSV,
    EXPAND_ROW,
    REVERT_COMPARE_DATA,
    TOGGLE_ACTIVE_SORT,
    UPDATE_REFERENCE_ID,
    SELECT_SINGLE_HSP,
    UPDATE_COLUMNS,
    SET_GLOBAL_FILTER_TAGS,
    SET_GLOBAL_FILTER_WORKLOADS,
    SET_GLOBAL_FILTER_SIDS,
    DRIFT_CLEAR_ALL_FILTERS
};
