const TOGGLE_CREATE_BASELINE_MODAL = 'TOGGLE_CREATE_BASELINE_MODAL';
const CREATE_BASELINE = 'CREATE_BASELINE';
const CLEAR_CREATE_BASELINE_DATA = 'CLEAR_CREATE_BASELINE_DATA';

export default {
    TOGGLE_CREATE_BASELINE_MODAL,
    CREATE_BASELINE,
    CLEAR_CREATE_BASELINE_DATA
};
