const EXPAND_PARENT_FACT = 'EXPAND_PARENT_FACT';
const FETCH_BASELINE_DATA = 'FETCH_BASELINE_DATA';
const CLEAR_EDIT_BASELINE_DATA = 'CLEAR_EDIT_BASELINE_DATA';
const PATCH_BASELINE = 'PATCH_BASELINE';
const DELETE_BASELINE_DATA = 'DELETE_BASELINE_DATA';
const SET_FACT_DATA = 'SET_FACT_DATA';
const TOGGLE_FACT_MODAL = 'TOGGLE_FACT_MODAL';
const SELECT_FACT = 'SELECT_FACT';
const CLEAR_ERROR_DATA = 'CLEAR_ERROR_DATA';
const EXPORT_BASELINE_DATA_TO_CSV = 'EXPORT_BASELINE_DATA_TO_CSV';

export default {
    EXPAND_PARENT_FACT,
    FETCH_BASELINE_DATA,
    CLEAR_EDIT_BASELINE_DATA,
    PATCH_BASELINE,
    DELETE_BASELINE_DATA,
    SET_FACT_DATA,
    TOGGLE_FACT_MODAL,
    SELECT_FACT,
    CLEAR_ERROR_DATA,
    EXPORT_BASELINE_DATA_TO_CSV
};
