const EXPAND_PARENT_FACT = 'EXPAND_PARENT_FACT';
const FETCH_BASELINE_DATA = 'FETCH_BASELINE_DATA';
const PATCH_BASELINE = 'PATCH_BASELINE';
const SET_FACT_DATA = 'SET_FACT_DATA';
const TOGGLE_EDIT_NAME_MODAL = 'TOGGLE_EDIT_NAME_MODAL';
const TOGGLE_FACT_MODAL = 'TOGGLE_FACT_MODAL';

export default {
    EXPAND_PARENT_FACT,
    FETCH_BASELINE_DATA,
    PATCH_BASELINE,
    SET_FACT_DATA,
    TOGGLE_EDIT_NAME_MODAL,
    TOGGLE_FACT_MODAL
};
