#!/bin/bash -e

read -p "Releasing QA to Prod (stable and beta)  environment. Do you wish to continue? (Y/n) " decision

remote_name=$(git remote -v | grep RedHatInsights --ignore-case | grep push | awk '{print $1}')

if [ $decision == 'Y' ];then
  git stash
  git fetch $remote_name
  git checkout qa
  git reset $remote_name/qa --hard
  git push $remote_name qa:prod
else
  echo 'Aborting release to prod'
fi
