const SELECT_HISTORIC_PROFILES = 'SELECT_HISTORIC_PROFILES';
const SET_SELECTED_HISTORIC_PROFILES = 'SET_SELECTED_HISTORIC_PROFILES';

export default {
    SELECT_HISTORIC_PROFILES,
    SET_SELECTED_HISTORIC_PROFILES
};
